// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCruBS4phj4rYPQTQFgzGM-5W83iqB-Y4Q',
    appId: '1:663777820227:web:dbd1936c7367da3f581ef6',
    messagingSenderId: '663777820227',
    projectId: 'feeder-dc220',
    authDomain: 'feeder-dc220.firebaseapp.com',
    storageBucket: 'feeder-dc220.firebasestorage.app',
    measurementId: 'G-45VDCPY4Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiSUuyN6Y6WBg9K6Y0efCziX77Sz_IHw',
    appId: '1:663777820227:android:668237d0b0222c3a581ef6',
    messagingSenderId: '663777820227',
    projectId: 'feeder-dc220',
    storageBucket: 'feeder-dc220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Iu6U7CT54NY83zBm-Ln3xxMA-tdM8HQ',
    appId: '1:663777820227:ios:aec543ed76a3825a581ef6',
    messagingSenderId: '663777820227',
    projectId: 'feeder-dc220',
    storageBucket: 'feeder-dc220.firebasestorage.app',
    iosBundleId: 'com.feeder.feeder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Iu6U7CT54NY83zBm-Ln3xxMA-tdM8HQ',
    appId: '1:663777820227:ios:aec543ed76a3825a581ef6',
    messagingSenderId: '663777820227',
    projectId: 'feeder-dc220',
    storageBucket: 'feeder-dc220.firebasestorage.app',
    iosBundleId: 'com.feeder.feeder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCruBS4phj4rYPQTQFgzGM-5W83iqB-Y4Q',
    appId: '1:663777820227:web:bed492c950fd7766581ef6',
    messagingSenderId: '663777820227',
    projectId: 'feeder-dc220',
    authDomain: 'feeder-dc220.firebaseapp.com',
    storageBucket: 'feeder-dc220.firebasestorage.app',
    measurementId: 'G-JBGZ06NV2R',
  );
}
